# Change these first
owner: dominion-it # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: Payroll (Live)
    url: https://live.dominionsystems.com/Payroll/applicantPostingListNL.aspx?code=time
  - name: Payroll (2Live)
    url: https://2live.dominionsystems.com/Payroll/applicantPostingListNL.aspx?code=time
  - name: Punch Monitor
    url: https://live.dominionsystems.com/punchmonitor/readpunches.aspx
  - name: Mobile Authentication Server
    url: https://auth2.dominionsystems.com/v4/.well-known/openid-configuration
  - name: Authentication Server
    url: https://auth2.dominionsystems.com/issue/wsfed
  - name: Mobile API (azure)
    url: https://dsmobileapi.azurewebsites.net/api/clock
  - name: Mobile API (dom-services)
    url: https://services.dominionsystems.com/mobile/api/clock
  - name: 2Mobile API (azure)
    url: https://dsmobile2api.azurewebsites.net/api/clock

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/dominion-it/uptime/master/static/img/icon.svg
  name: Dominion Systems
  introTitle: "Dominion Systems. PAYROLL & HR. ONE PLATFORM."
  introMessage: This is the uptime monitor and status page for [Dominion Systems](https://dominionsystems.com), powered by [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Dominion Systems
      href: https://dominionsystems.com
    - title: DS Live
      href: https://live.dominionsystems.com/payroll
    - title: DS 2Live
      href: https://2live.dominionsystems.com/payroll
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
